### ISSUE TITLE
Название и детали

### ISSUE THREAD

**Issue by lkoida-boohoo** [morozandrei/css#1]
https://github.com/morozandrei/css/blob/7bf7b2b0d8f82fd1046060cc5119e06ee68cbde5/float-simple.css#L10
обычно, при использовании очищающих свойств для флоатов, используют класс
```css
.clearfix {
  clear:both;
}
```
это позволяет переиспрользовать этот метод в нескольких местах.
